### PR TITLE
Voltage limit override new version

### LINKED ISSUE #26: VoltageLimitOverride version 2
### Describe the current behavior

For the moment, we have as parameters:
````
Map<String, VoltageLimitOverride> specificVoltageLimits = new HashMap<>();
specificVoltageLimits.put("JAZENP1", new VoltageLimitOverride(-5, 5));
specificVoltageLimits.put("JAZENP4", new VoltageLimitOverride(-5, 5));
specificVoltageLimits.put("BRAEKP1", new VoltageLimitOverride(-5, 5));
````
But, it does not work for:
- Voltage levels without any low or high voltage limit. The AMPL has a default behavior in that case (but not ideal).
- Voltage levels with just a high or a low voltage limit. It throws during Java integration if we try to override (and it is normal).
````
Exception in thread "main" com.powsybl.commons.PowsyblException: Voltage level 'JAZENP1' has only one voltage limit defined (min:19.0, max:NaN). Please define none or both.
	at com.powsybl.openreac.parameters.input.OpenReacParameters.checkIntegrity(OpenReacParameters.java:206)
	at com.powsybl.openreac.OpenReacRunner.run(OpenReacRunner.java:46)
````

### Describe the expected behavior

1) The integrity test must be done also for voltage levels without any voltage limit (both case).
2) It could be better not to throw but to add a log with all the issues and throw (or return a false status in the result).
3) Increase the class `VoltageLimitOverride`. 
- Add a boolean that says if low limit is absolute or relative ;
- Add a boolean that says if high limit is absolute or relative ;
- Change the constructor to take the 2 booleans and 2 values (that could be relative or absolute) ;
-  `getDeltaLowVoltageLimit()` and `getDeltaHighVoltageLimit()` must return Optional ;
- Add 2 new methods `getLowVoltageLimit()` and  `getDeltaHighVoltageLimit()` that returns Optional.

### Describe the motivation

_No response_

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by p-arvy**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

### CODE REVIEW

File: open-reac/src/main/java/com/powsybl/openreac/OpenReacTool.java [hunk 1]
```diff
@@ -165,7 +165,9 @@ public OpenReacParameters createOpenReacParameters(CommandLine line,
                 String voltageId = node.get("id").asText();
                 double lowerPercent = node.get("lower").asDouble();
                 double upperPercent = node.get("upper").asDouble();
-                openReacParameters.addSpecificVoltageLimits(Map.of(voltageId, new VoltageLimitOverride(lowerPercent, upperPercent)));
```
Comment (annetill) [inline open-reac/src/main/java/com/powsybl/openreac/OpenReacTool.java:168]: @geofjamg can we delete the tool now? If yes, I will dot that in a other PR.

File: open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideSerializer.java [hunk 2]
```diff
@@ -26,8 +26,10 @@ public VoltageLimitOverrideSerializer() {
     @Override
     public void serialize(VoltageLimitOverride voltageLimitOverride, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException {
         jsonGenerator.writeStartObject();
-        jsonGenerator.writeNumberField("deltaLowVoltageLimit", voltageLimitOverride.getDeltaLowVoltageLimit());
-        jsonGenerator.writeNumberField("deltaHighVoltageLimit", voltageLimitOverride.getDeltaHighVoltageLimit());
+        jsonGenerator.writeObjectField("voltageLevelId", voltageLimitOverride.getVoltageLevelId());
```
Comment (colinepiloquet) [inline open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideSerializer.java:29]: Here you can use :
```
jsonGenerator.writeStringField("voltageLevelId" voltageLimitOverride.getVoltageLevelId());
jsonGenerator.writeStringField("voltageLimitType", voltageLimitOverride.getVoltageLimitType().name();
jsonGenerator.writeBooleanField("isRelative", voltageLimitOverride.isRelative());
jsonGenerator.writeNumberField("value", voltageLimitOverrride.getLimit());
```

File: open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideDeserializer.java [hunk 3]
```diff
@@ -26,23 +26,33 @@ public VoltageLimitOverrideDeserializer() {
 
     @Override
     public VoltageLimitOverride deserialize(JsonParser parser, DeserializationContext deserializationContext) throws IOException {
-        double deltaLowVoltageLimit = 0;
-        double deltaHighVoltageLimit = 0;
+        String voltageLevelId = null;
+        VoltageLimitOverride.VoltageLimitType type = null;
+        boolean isRelative = true;
+        double overrideValue = 0;
```
Comment (colinepiloquet) [inline open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideDeserializer.java:32]: You might want to initialize to Double.NaN and then the check that the value is in the file will be done when calling the constructor.

File: open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideDeserializer.java [hunk 4]
```diff
@@ -26,23 +26,33 @@ public VoltageLimitOverrideDeserializer() {
...
                     break;
-                case "deltaHighVoltageLimit":
+                case "voltageLimitType":
                     parser.nextToken();
-                    deltaHighVoltageLimit = parser.readValueAs(Double.class);
+                    type = parser.readValueAs(VoltageLimitOverride.VoltageLimitType.class);
+                    break;
+                case "isRelative":
+                    parser.nextToken();
+                    isRelative = parser.readValueAs(boolean.class);
```
Comment (colinepiloquet) [inline open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideDeserializer.java:46]: Use `Boolean.class`.

File: open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideDeserializer.java [hunk 5]
```diff
@@ -26,23 +26,33 @@ public VoltageLimitOverrideDeserializer() {
 
     @Override
     public VoltageLimitOverride deserialize(JsonParser parser, DeserializationContext deserializationContext) throws IOException {
-        double deltaLowVoltageLimit = 0;
-        double deltaHighVoltageLimit = 0;
+        String voltageLevelId = null;
+        VoltageLimitOverride.VoltageLimitType type = null;
+        boolean isRelative = true;
```
Comment (colinepiloquet) [inline open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideDeserializer.java:31]: You might also want to initialize this boolean to null, for that you can use Boolean instead. Or do you want isRelative to have a default value to true if the field is not in the file? 
Then you can add a check that isRelative is well defined and if not throw an exception because it's undefined.

Comment (annetill) [reply open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideDeserializer.java:31]: ok great, you are right.

File: open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideDeserializer.java (hunk 3 above)
Comment (annetill) [reply open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideDeserializer.java:32]: Yes, but @p-arvy value must be defined ad so checked at construction.

File: open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideDeserializer.java (hunk 4 above)
Comment (annetill) [reply open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideDeserializer.java:46]: ok

File: open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideSerializer.java (hunk 2 above)
Comment (annetill) [reply open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/VoltageLimitOverrideSerializer.java:29]: ok, thanks!

**Review by colineplqt — APPROVED** [review]

**Review by annetill — APPROVED** [review]
